id: http-header-misconfiguration
info:
  name: HTTP Header Misconfiguration
  author: Your Name
  severity: medium
  description: Identifies headers exposing sensitive server information.

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: regex
        regex:
          - "Server: .*"
          - "X-Powered-By: .*"
      - type: word
        words:
          - "Apache"
          - "nginx"
          - "PHP"
